[platform]
id = 2
name = "Sega Genesis"
short_name = "GENESIS"

[address]
bits = 24
max = 0xFFFFFF

[data]
bits = 16

[compare]
supported = false

[defaults]
patch_type = "REPLACE"
flags = { compare_enabled = false, wide_data = false, read_only = false, persistent = false }
