[platform]
id = 0
name = "Nintendo Entertainment System"
short_name = "NES"

[address]
bits = 15
max = 0x7FFF

[data]
bits = 8

[compare]
supported = true

[defaults]
patch_type = "REPLACE"
flags = { compare_enabled = false, wide_data = false, read_only = false, persistent = false }
